# Generated by Django 4.1.7 on 2023-04-11 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('mr', 'MR'), ('mad', 'MADAM'), ('dir', 'DIRECTOR'), ('MD', 'MANAGER')], max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PendingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=50)),
                ('job_title', models.CharField(choices=[('FD', 'FUEL DISPENSER'), ('ELEC', 'ELECTRICALS'), ('TANK', 'TANK FARM'), ('GEN', 'GENERATOR'), ('LIGHTING', 'ELLUMINATION'), ('TOTTEM', 'FLAGPOLE')], default='Fuel Dispenser', max_length=50)),
                ('problem_reported', models.CharField(blank=True, max_length=1080, null=True)),
                ('part_required', models.CharField(blank=True, max_length=500, null=True)),
                ('assigned_time', models.DateTimeField(auto_now_add=True)),
                ('job_status', models.BooleanField(default=False)),
                ('assigned_by', models.ForeignKey(default='Name', on_delete=django.db.models.deletion.CASCADE, to='todo.departmenthead')),
            ],
        ),
    ]
